<?php

// Generated by scripts/write-vite-assets.mjs — do not edit.
return [
    'version' => 1781676541,
    'css' =>     [
        "/build/assets/app-Bv4Or8Yc.css"
    ],
    'js' =>     [
        "/build/assets/app-CtPHNUbh.js"
    ],
];
