<?php

// Generated by scripts/write-vite-assets.mjs — do not edit.
return [
    'css' =>     [
        "/build/assets/app-BwczjG6N.css"
    ],
    'js' =>     [
        "/build/assets/app-BMrFYmEF.js"
    ],
];
