<?php

// Generated by scripts/write-vite-assets.mjs — do not edit.
return [
    'css' =>     [
        "/build/assets/app-u5J6gsHD.css"
    ],
    'js' =>     [
        "/build/assets/app-CBJxjIAt.js"
    ],
];
